:logfile: log/sidekiq.log
:concurrency: 5
:queues:
  - [default, 2]
  - [recompletion, 2]
  - [facebook_feed, 2]
  - [report_scheduler, 2]
  - [lyst_feed, 2]
  - [sitemap, 2]
  - [reviews_io_feed, 2]
  - [store_products, 2]
  - [base_currency_products_price, 6]
  - [client_products_price, 6]
  - [reindex_es_products, 6]
  - [vendor_products_price, 6]
  - [product_prices, 4]
  - [secondary_product_prices, 6]
  - [client_currency_prices, 6]
  - [auto_exchange_rates, 6]
  - [page_builder, 6]
  - [dashboard_reporting, 6]
  - [line_item_variant_reporting, 6]
  - [store_product_image_variant, 6]
  - [ts_gift_cards, 6]
  - [ts_givex_cards_generator, 4]
  - [ses_emails_data, 6]
  - [send_ses_emails, 6]
  - [fullfill_digital_shipment, 6]
  - [auto_book_lalamove, 2]
  - [mark_order_with_lalamove_status, 2]
  - [schedule_sales_reports, 2]
  - [finance_feed, 2]
  - [expired_sale_products, 2]
  - [send_sms, 2]
  - [cards_to_be_generated_and_delivered, 2]
  - [update_currency_price, 6]
  - [scheduled_reports_queue, 2]
  - [scheduled_reports_ses_queue, 2]
  - [mixpanel, 2]
  - [error_logging, 2]
  - [batch_crud, 8]
  - [spree_stock_location_stock_items, 6]
  - [spree_webhooks, 6]
  - [system_reports_queue, 2]
  - [brim_report, 2]
  - [upload_image, 2]
  - [whitelist_email_queue, 2]
development:
  :concurrency: 15
staging:
production:
